config/routes.rb
Rails.application.routes.draw do

  get 'invitations/create'

  get 'invitations/destroy'

  get 'invites/create'

  get 'invites/destroy'

  resources :trips

  devise_for :users
  resources :users, only: [:index, :show]
  root 'pages#home'
  get 'about' => 'pages#about'

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
	#create the join model between users and trips.  This covers the trips that users go on, but don't create.
	belongs_to :attendee, class_name: "User"
	belongs_to :attended_trip, class_name: "Trip"
end

app/models/trip.rb
class Trip < ActiveRecord::Base

	#this part covers all the trips the user creates.  they're different from the ones that they just attend
	belongs_to :user

	#set up has_many :through relationship with the trips made by other users.  Invitations is the join table.
	has_many :invitations, :foreign_key => :attended_trip_id
	has_many :attendees, :through => :invitations 


	validates :location, presence: true

	#I apparently need to update this gem.  I don't know how to do that so I hope the developer does.
	validates_date :ends_on, :on_or_after => :starts_on, :on_or_after_message => 'must be on or after starts on date'
	
	#this basically ensures that we get both the trips that the user made and the trips 
	#that the user went on, while discarding duplicates.  This was originally written by John Maxwell.  Given the way I've started setting this up, I'll need to change this.
	#scope :for_user, -> (user) {
	#	joins("left outer join trips_users on trips.id=trips_users.trip_id").
	#		where("trips_users.user_id = ? OR trips.created_by = ?", user.id, user.id).
	#		uniq
	#}

	scope :for_user, -> (user) {
		joins("left outer join invitations on trips.id=invitations.attended_trip_id").where("invitations.attendee_id= ? OR trips.user_id = ?", user.id, user.id).uniq
	}

	#The scope Lambda immediately above is apparently preferred because it is only a single database query, where the method below includes two separate queries.
	#def self.for_user(user)
	# 	(user.trips + user.attended_trips).uniq
	#end

	#methods necessary to get latitude and longitude for the location
	geocoded_by :location
	after_validation :geocode

	#calculates the number of meals needed for the trip
    def calculate_meals
      
      t1 = self.starts_on.to_time.to_i
      t2 = self.ends_on.to_time.to_i

      seconds = t2-t1
      days = seconds / 86400

      self.meals = days * 3

    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #This shows that a user can create many trips.  the :foreign_key statement may be redundant since I'm separately saving a creator_id in the trips controller
  has_many :trips, :foreign_key => :user_id

  #this describes the relationship the user can have with other people's trips.
  has_many :invitations, :foreign_key => :attendee_id
  has_many :attended_trips, :through => :invitations

  #Validations
  validates :name, presence: true, length: {maximum: 50}
  
  #email validations
  before_save { self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
    uniqueness: {case_sensitive: false}


  
  #statement required by paperclip.  show what images get created in the DB when an image is uploaded, and sets the default image
  has_attached_file :avatar, 
  	:styles => { 
  		:header => "24x24#", 
  		:small => "52x52#", 
  		:medium => "300x300#", 
  		:thumb => "100x100#" }, 
  		:default_url => "/images/default_user_:style.jpg"
  
  #image validation to make sure that what's being uploaded is in fact an image
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  #User Methods

  #Select all users from the database except a specified user
  def self.all_except(user)
    where.not(id: user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  	devise_parameter_sanitizer.for(:account_update) << :avatar
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, only: [:show, :edit, :update, :destroy]


  def index

    #something is happening here that is causing the application to forget who the user is temporarily.  This apparently only happens if the user attends trips but doesn't actually own any.

    @user = current_user

    @pending_trips = Trip.for_user(@user).where("starts_on >= ?", Time.now).order("starts_on ASC")
    @past_trips = Trip.for_user(@user).where("starts_on < ?", Time.now).order("starts_on ASC")
  end

  def show
    @creator = User.find(@trip.created_by)
  end

  def new
    @trip = current_user.trips.new
    @users = User.all_except(current_user)
  end

  def edit
    @user = User.find(@trip.created_by)
    @users = User.all_except(current_user)
    if current_user != @user
      redirect_to root_url, notice: "That's not your trip to edit!"
    end 
  end

  def create
    @trip = current_user.trips.new(trip_params)
    @trip.created_by = current_user.id
    @trip.calculate_meals

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    @trip.calculate_meals

    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

      #should do some validation here to ensure that the user is the right user
      @trip.destroy
      respond_to do |format|
        format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
        format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:location, :description, :name, :starts_on, :ends_on, :improvements, :attendee_ids => [])
    end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :set_user, only: [:show]

  def index
  	@users = User.all
  end

  def show
    #@usertrips = @user.trips.all
    @usertrips = Trip.for_user(@user).order("starts_on ASC")
    @hash = Gmaps4rails.build_markers(@usertrips) do |trip, marker|
      marker.lat trip.latitude
      marker.lng trip.longitude
      marker.infowindow trip.location
    end
  end

  private

  	def set_user
  		@user = User.find(params[:id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Hikeabl"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/form_helper.rb
# app/helpers/form_helper
module FormHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trips_helper.rb
module TripsHelper

	#I need to build a creator name helper that will let me find 
	#the name of the creator and display it in the view based on 
	#the @trip.created_by id.

	def creator_name(num)
		creator = User.find(num).name
		creator
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "hikeabl.", root_path, class: "navbar-brand" %>
  </div>

	<!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      

      <% if user_signed_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= image_tag current_user.avatar.url(:header), class: "img-circle"%>  <%= current_user.email %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Your Profile", current_user %></li>
            <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Your Trips", trips_path %></li>
            <li><%= link_to "New Trip", new_trip_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      

      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>

      
    </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>

	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<div class="panel panel-default drop-shadow">
	<div class="panel-body">
		<h3>At hikeabl, we're about bringing people together.</h3>

		<h4>Do you love to hike?  Great.  Share where you've been and what you did.  We want to know.</h4>
	</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to hikeabl!</h1>

	<% if user_signed_in? %>
		<h3>You are signed in as <%= current_user.name %>.  Congratulations.  You are a genius.  Mess around with the toolbar above to get started.</h3>
	<% else %>
		<h3><%= link_to "Sign up", new_user_registration_path %> for hikeabl.</h3>
	<% end %>
</div>

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>
    <% if @trip.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

        <ul>
        <% @trip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :location %>
      <%= f.text_field :location, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :starts_on %>
      <%= f.date_select :starts_on, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :ends_on %>
      <%= f.date_select :ends_on, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :improvements %>
      <%= f.text_area :improvements, class: "form-control" %>
    </div>

    <h2>Who went on the trip?</h2>

    	<%= hidden_field_tag "trip[attendee_ids][]" %>
      <%- @users.each do |user| -%>
        <div>
      		<label>
        		<%= check_box_tag "trip[attendee_ids][]", user.id, @trip.attendees.include?(user) -%>
        		<%= user.name -%>
      		</label>
        </div>
    	<%- end -%>
     <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<% provide(:title, 'Trip Index') %>
<div class="row">
  <div class="col-md-6">
    <h1>Listing your trips</h1>
  </div>
  <div class="col-md-6">
    <%= link_to 'New Trip', new_trip_path, class: "btn btn-default btn-lg pull-right" %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">

    <p class="lead">Pending Trips</p>
    <% if @pending_trips.any? %>
      <% @pending_trips.each do |trip| %>
        <div class="panel panel-success drop-shadow">
          <div class="panel-heading"><h3 class="panel-title"><%= link_to trip.location, trip %></h3>
          <p><%= trip.starts_on.strftime("%B #{trip.starts_on.day.ordinalize}, %Y") %> - <%= trip.ends_on.strftime("%B #{trip.ends_on.day.ordinalize}, %Y") %></p>
          <p><strong>Created By:</strong> <%= creator_name(trip.created_by) %></p>
          <p><strong>Attendees:</strong></p>
            <% trip.attendees.each do |user| %>
              <%= link_to user.name, user %>
            <% end %>
          </div>

          <div class="panel-body">


            <p>
              <strong>Duration:</strong>
              <%= distance_of_time_in_words(trip.starts_on, trip.ends_on) %>
            </p>

            <p>
              <strong>Description:</strong>
              <%= trip.description %>
            </p>

            <% if trip.improvements? %>
              <p>
                <strong>What do you wish you had done differently?</strong><br />
                <%= trip.improvements %>
              </p>
            <% end %>
          </div>

          <div class="panel-footer">
            <%= link_to 'Show', trip %> |
            <% if current_user.id = trip.created_by %>
              <%= link_to 'Edit', edit_trip_path(trip) %> |
              <%= link_to 'Destroy', trip, method: :delete, data: {confirm: 'Are you sure?  Clicking OK will permanently delete this trip.'} %>
            <% end %>
          </div>
        </div>

      <% end %>
    <% else %>
      <p>You don't have any pending trips!</p>
    <% end %>
  </div>

  <div class="col-md-6">

    <p class="lead">Past Trips</p>
    <% if @past_trips.any? %>
      <% @past_trips.each do |trip| %>
        <div class="panel panel-default drop-shadow">
          <div class="panel-heading"><h3 class="panel-title"><%= link_to trip.location, trip %></h3>
          <p><%= trip.starts_on.strftime("%B #{trip.starts_on.day.ordinalize}, %Y") %> - <%= trip.ends_on.strftime("%B #{trip.ends_on.day.ordinalize}, %Y") %></p>
          <p><strong>Created By:</strong> <%= creator_name(trip.created_by) %></p>
          <p><strong>Attendees:</strong></p>
            <% trip.attendees.each do |user| %>
              <%= link_to user.name, user %> 
            <% end %>
          </div>

          <div class="panel-body">


            <p>
              <strong>Duration:</strong>
              <%= distance_of_time_in_words(trip.starts_on, trip.ends_on) %>
            </p>

            <p>
              <strong>Description:</strong>
              <%= trip.description %>
            </p>

            <% if trip.improvements? %>
              <p>
                <strong>What do you wish you had done differently?</strong><br />
                <%= trip.improvements %>
              </p>
            <% end %>
          </div>

          <div class="panel-footer">
            <%= link_to 'Show', trip %> |
            <% if current_user.id = trip.created_by %>
              <%= link_to 'Edit', edit_trip_path(trip) %> |
              <%= link_to 'Destroy', trip, method: :delete, data: {confirm: 'Are you sure?  Clicking OK will permanently delete this trip.'} %>
            <% end %>
          </div>
        </div>

      <% end %>
    <% else %>
      <p>You've never been on a trip before?!</p>
    <% end %>
  </div>
</div>

app/views/trips/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>New trip</h1>
	</div>

	<div class="panel-body">
		<%= render 'form' %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Back', trips_path %>
	</div>
</div>

app/views/trips/show.html.erb
<% provide(:title, @trip.name) %>



<div class="panel panel-default drop-shadow">
	<div class="panel-heading"><h3 class="panel-title">Showing the trip to <%= @trip.location %></h3>
	<p><%= @trip.starts_on.strftime("%B #{@trip.starts_on.day.ordinalize}, %Y") %> - <%= @trip.ends_on.strftime("%B #{@trip.ends_on.day.ordinalize}, %Y") %></p>
	<p><strong>Created by: </strong><%= @creator.name %></p>
	<p><strong>Attendees:</strong>
	<ul class="list-inline">
		<% @trip.attendees.each do |attendee| %>
			<li><%= link_to image_tag(attendee.avatar.url(:thumb), :title => "This is #{attendee.name}.", :class => "img-circle"), attendee %></li>
		<% end %>
	</ul>
	</div>

	<div class="panel-body">


		<p>
			<strong>Duration:</strong>
			<%= distance_of_time_in_words(@trip.starts_on, @trip.ends_on) %>
		</p>

		<p>
			<strong>Number of meals you should pack:</strong>
			<%=@trip.meals%> per person
		</p>

		<p>
		  <strong>Description:</strong>
		  <%= @trip.description %>
		</p>

		<% if @trip.improvements? %>
			<p>
				<strong>What do you wish you had done differently?</strong><br />
				<%= @trip.improvements %>
			</p>
		<% end %>
	</div>

	<div class="panel-footer">

		<% if current_user = @user %>
			<%= link_to 'Edit', edit_trip_path(@trip) %> |
		<% end %>
		<%= link_to 'Back', trips_path %>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'User Index') %>

<div class="panel panel-default drop-shadow">
  <div class="panel-heading">
    <h1>Listing Users</h1>
  </div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th>User</th>
          <th>Email</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.avatar.url(:small), class: "img-circle"%>
            <td><%= link_to user.name, user %></td>
            <td><%= user.email %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
   </div>
</div>

app/views/users/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-5">



    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><%=@user.name%></h3>
      </div>
      <div class="panel-body center">
        <%= image_tag(@user.avatar.url(:medium), :title => "This is #{@user.name}.", :class => "img-rounded")%>  
      </div>
    </div>
  </div>

  <div class="col-md-7">



    <div class="panel panel-default drop-shadow">
      <div class="panel-heading">
        <h3><%=@user.name %>'s Trips</h3>
      </div>
      <div class="panel-body">
        <% if @usertrips.any? %>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Location</th>
                <th>Date Range</th>
              </tr>
            </thead>

            <tbody>
              <% @usertrips.each do |trip| %>
                <tr>
                  <td><%= link_to trip.location, trip %></td>
                  <td><%= trip.starts_on.strftime("%B #{trip.starts_on.day.ordinalize}, %Y") %> - <%= trip.ends_on.strftime("%B #{trip.ends_on.day.ordinalize}, %Y") %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p><%= @user.name.upcase %> DON'T HAVE NO TRIPS! </p>
        <% end %>
       </div>
    </div>
  </div>
</div>

<div class="container center">
  <div id="map" style='width: 100%; height: 400px;'></div>
</div>

<script type='text/javascript'>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>